apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-job
spec:
  template:
    metadata:
      name: countdown-job
    spec:
      containers:
        - name: container-countdown-job
          image: debian:latest
          command: ["/bin/sh", "-c"]
          args:
            [
              "for i in ten nine eight seven six five four three two one ; do echo $i ; done",
            ]
      restartPolicy: Never
