apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30082
  selector:
    app: web-app
  